Demo mobitru integration
qavajs/demo pull request #12
Opened 2022-11-18 10:05 UTC by DPrakapuk

added additional folder for integration with mobitru service

2022-11-24 08:44 UTC, AlexGalichenko requested changes

2022-11-24 08:44 UTC, AlexGalichenko commented on mobile-web/mobitru.js
> +        service: [appiumConfig],
appiumConfig is not needed here

2022-11-24 08:44 UTC, AlexGalichenko commented on mobile-web/mobitru.js
> +const appiumConfig = wdioService([
appium config is not needed here

2022-11-25 10:21 UTC, nomid0612 commented on mobile-web/mobitru.js
> +const appiumConfig = wdioService([
removed

2022-11-25 10:21 UTC, nomid0612 commented on mobile-web/mobitru.js
> +        service: [appiumConfig],
removed

2022-11-25 10:33 UTC, KirillBogdanets approved these changes

2022-11-26 15:46 UTC, AlexGalichenko approved these changes

2022-12-01 06:06 UTC, merged